version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
environment:
  Module: J81.ADCToolkit
  Modules: J81.ADCToolkit,J81.ADCToolkit.Conf,J81.ADCToolkit.Stat
  Source: J81.ADCToolkit
  GitHubKey:
    secure: ${{ secrets.GitHubKey }}
  NuGetApiKey:
    secure: ${{ secrets.NuGetApiKey }}
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\GitHub.ps1
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
- ps: . .\ci\GitHub.ps1
deploy_script:
- ps: . .\ci\Deploy.ps1

skip_commits:
  message: /AppVeyor validate.*|Merge branch 'main' of.*|Update docs.*/

only_commits:
  files:
    - J81.ADCToolkit/**/*
