#
# Module manifest for module 'PSGet_J81.ADCToolkit.Stat'
#
# Generated by: John Billekens
#
# Generated on: 23-10-2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'J81.ADCToolkit.Stat.psm1'

    # Version number of this module.
    ModuleVersion     = '2210.2317'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '5c238dd4-26d6-4e9b-bba8-187e7f0342d5'

    # Author of this module
    Author            = 'John Billekens'

    # Company or vendor of this module
    CompanyName       = 'J81-Blog'

    # Copyright statement for this module
    Copyright         = '(c) 2022 John Billekens. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Citrix ADC PowerShell Toolkit, Modules for managing Citrix ADC from PowerShell'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @("J81.ADCToolkit", @{ModuleName = "J81.ADCToolkit"; RequiredVersion = "2210.2317"; GUID = "548c9f18-6ad5-4aff-8760-39e1fc720d57" })

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'Invoke-ADCGetAaaStats',
    'Invoke-ADCGetAppflowStats', 
    'Invoke-ADCGetAppfwStats',
    'Invoke-ADCGetAppfwpolicyStats', 
    'Invoke-ADCGetAppfwpolicylabelStats', 
    'Invoke-ADCGetAppfwprofileStats',
    'Invoke-ADCGetAppqoeStats', 
    'Invoke-ADCGetAppqoepolicyStats',
    'Invoke-ADCGetAuditStats', 
    'Invoke-ADCGetAuthenticationloginschemapolicyStats', 
    'Invoke-ADCGetAuthenticationoauthidppolicyStats', 
    'Invoke-ADCGetAuthenticationpolicyStats', 
    'Invoke-ADCGetAuthenticationpolicylabelStats', 
    'Invoke-ADCGetAuthenticationsamlidppolicyStats', 
    'Invoke-ADCGetAuthenticationvserverStats', 
    'Invoke-ADCGetAuthorizationpolicylabelStats', 
    'Invoke-ADCGetAutoscalepolicyStats',
    'Invoke-ADCGetServiceStats', 
    'Invoke-ADCGetServicegroupStats', 
    'Invoke-ADCGetServicegroupmemberStats',
    'Invoke-ADCGetBotStats', 
    'Invoke-ADCGetBotpolicyStats',
    'Invoke-ADCGetBotpolicylabelStats', 
    'Invoke-ADCGetBotprofileStats',
    'Invoke-ADCGetCacheStats', 
    'Invoke-ADCGetCachecontentgroupStats', 
    'Invoke-ADCGetCachepolicyStats', 
    'Invoke-ADCGetCachepolicylabelStats', 
    'Invoke-ADCGetClusterinstanceStats', 
    'Invoke-ADCGetClusternodeStats',
    'Invoke-ADCGetCmpStats', 
    'Invoke-ADCGetCmppolicyStats',
    'Invoke-ADCGetCmppolicylabelStats', 
    'Invoke-ADCGetContentinspectionStats', 
    'Invoke-ADCGetContentinspectionpolicyStats', 
    'Invoke-ADCGetContentinspectionpolicylabelStats', 
    'Invoke-ADCGetCrvserverStats',
    'Invoke-ADCGetCsvserverStats', 
    'Invoke-ADCGetDnsStats',
    'Invoke-ADCGetDnspolicylabelStats', 
    'Invoke-ADCGetDnsrecordsStats',
    'Invoke-ADCGetDosStats', 
    'Invoke-ADCGetDospolicyStats',
    'Invoke-ADCGetFeoStats', 
    'Invoke-ADCGetGslbdomainStats',
    'Invoke-ADCGetGslbserviceStats', 
    'Invoke-ADCGetGslbservicegroupStats', 
    'Invoke-ADCGetGslbservicegroupmemberStats', 
    'Invoke-ADCGetGslbsiteStats',
    'Invoke-ADCGetGslbvserverStats', 
    'Invoke-ADCGetHanodeStats', 
    'Invoke-ADCGetIcapolicyStats', 
    'Invoke-ADCGetIpseccountersStats', 
    'Invoke-ADCGetIpsecalgcountersStats', 
    'Invoke-ADCGetLbvserverStats', 
    'Invoke-ADCGetLldpStats', 
    'Invoke-ADCGetLsnStats', 
    'Invoke-ADCGetLsndsliteStats', 
    'Invoke-ADCGetLsngroupStats', 
    'Invoke-ADCGetLsnnat64Stats', 
    'Invoke-ADCGetLsnpoolStats', 
    'Invoke-ADCGetBridgeStats', 
    'Invoke-ADCGetInatStats', 
    'Invoke-ADCGetInatsessionStats', 
    'Invoke-ADCGetInterfaceStats', 
    'Invoke-ADCGetMapbmrStats', 
    'Invoke-ADCGetMapdomainStats', 
    'Invoke-ADCGetNat64Stats', 
    'Invoke-ADCGetRnatStats', 
    'Invoke-ADCGetRnat6Stats', 
    'Invoke-ADCGetRnatipStats', 
    'Invoke-ADCGetTunnelipStats', 
    'Invoke-ADCGetTunnelip6Stats', 
    'Invoke-ADCGetVlanStats',
    'Invoke-ADCGetVxlanStats', 
    'Invoke-ADCGetNsStats',
    'Invoke-ADCGetNsaclStats', 
    'Invoke-ADCGetNsacl6Stats',
    'Invoke-ADCGetNslimitidentifierStats', 
    'Invoke-ADCGetNsmemoryStats',
    'Invoke-ADCGetNspartitionStats', 
    'Invoke-ADCGetNspbrStats',
    'Invoke-ADCGetNspbr6Stats', 
    'Invoke-ADCGetNssimpleaclStats',
    'Invoke-ADCGetNssimpleacl6Stats', 
    'Invoke-ADCGetNstrafficdomainStats',
    'Invoke-ADCGetPcpserverStats', 
    'Invoke-ADCGetPqStats',
    'Invoke-ADCGetPqpolicyStats', 
    'Invoke-ADCGetProtocolhttpStats',
    'Invoke-ADCGetProtocolhttp2Stats', 
    'Invoke-ADCGetProtocolicmpStats', 
    'Invoke-ADCGetProtocolicmpv6Stats',
    'Invoke-ADCGetProtocolipStats', 
    'Invoke-ADCGetProtocolipv6Stats',
    'Invoke-ADCGetProtocolmptcpStats', 
    'Invoke-ADCGetProtocoltcpStats',
    'Invoke-ADCGetProtocoludpStats', 
    'Invoke-ADCGetQosStats',
    'Invoke-ADCGetResponderpolicyStats', 
    'Invoke-ADCGetResponderpolicylabelStats', 
    'Invoke-ADCGetRewritepolicyStats', 
    'Invoke-ADCGetRewritepolicylabelStats',
    'Invoke-ADCGetScStats', 
    'Invoke-ADCGetScpolicyStats',
    'Invoke-ADCGetSnmpStats', 
    'Invoke-ADCGetSpilloverpolicyStats',
    'Invoke-ADCGetSslStats', 
    'Invoke-ADCGetSslvserverStats', 
    'Invoke-ADCGetStreamidentifierStats',
    'Invoke-ADCGetSystemStats', 
    'Invoke-ADCGetSystembwStats',
    'Invoke-ADCGetSystemcpuStats', 
    'Invoke-ADCGetSystemmemoryStats', 
    'Invoke-ADCGetTmsessionpolicyStats', 
    'Invoke-ADCGetTmtrafficpolicyStats', 
    'Invoke-ADCGetTransformpolicyStats', 
    'Invoke-ADCGetTransformpolicylabelStats', 
    'Invoke-ADCGetTunneltrafficpolicyStats', 
    'Invoke-ADCGetUservserverStats', 
    'Invoke-ADCGetVideooptimizationStats', 
    'Invoke-ADCGetVideooptimizationdetectionpolicyStats', 
    'Invoke-ADCGetVideooptimizationdetectionpolicylabelStats', 
    'Invoke-ADCGetVideooptimizationpacingpolicyStats', 
    'Invoke-ADCGetVideooptimizationpacingpolicylabelStats', 
    'Invoke-ADCGetVpnStats',
    'Invoke-ADCGetVpnurlpolicyStats', 
    'Invoke-ADCGetVpnvserverStats'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    # VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        #RepositorySourceLocation of this module
        RepositorySourceLocation = 'https://github.com/j81blog/J81.ADCToolkit/'

        PSData                   = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = 'J81-Blog', 'NetScaler', 'Citrix', 'ADC', 'PowerShell'

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/j81blog/J81.ADCToolkit/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/j81blog/J81.ADCToolkit/'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/j81blog/J81.ADCToolkit/blob/master/CHANGELOG.md'

            # External dependent modules of this module
            # ExternalModuleDependencies = ''

        } # End of PSData hashtable
    
    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
